import TexturedBg from "../../../components/ui/TexturedBg";

export default function AboutHorion() {
  return (
    <section className="side-padding my-container max-w-[1200px]! grid lg:grid-cols-2 cards-gap justify-items-center">
      {/* card 1 */}
      <div className="relative flex max-w-[550px] w-full flex-col justify-between lg-rounded overflow-hidden border border-blueish-gray/25">
        {/* bg */}
        <TexturedBg color="var(--color-gold)" />

        {/* img */}
        <div className="flex justify-end relative lg:pt-6 pt-4">
          <img
            className="w-4/5"
            src="/assets/demos/horion-for-sales/ask-ai.png"
          />
        </div>

        {/* text */}
        <div className="lg:p-6 p-4 pt-0! relative lg:space-y-3 space-y-1.5">
          <p className="text-28 w-9/10">
            AI that answers questions for you, real time
          </p>
          <p className="text-18 opacity-70 leading-[1.2]! w-9/10">
            Cluely uses the screen, transcript, and AI to answer questions for
            you, live.
          </p>
        </div>
      </div>

      {/* card 2 */}
      <div
        className="relative flex max-w-[550px] w-full flex-col justify-between lg-rounded overflow-hidden bg-blueish-gray/15 border border-blueish-gray/25  "
        style={{ boxShadow: "inset 0 0 10px white" }}
      >
        {/* text */}
        <div className="lg:p-6 p-4 pb-0! relative lg:space-y-3 space-y-1.5">
          <p className="text-28 ">Instant follow-up emails</p>
          <p className="text-18 opacity-70 leading-[1.2]! w-9/10">
            Send perfectly drafted follow-up emails within seconds after every
            call.
          </p>
        </div>

        {/* img */}
        <div className="flex relative">
          <img
            className="w-9/10 translate-y-4"
            src="/assets/demos/horion-for-sales/follow-up-emails.png"
          />
        </div>
      </div>

      {/* card 3 */}
      <div
        className="relative flex max-sm:flex-col max-w-[550px] w-full justify-between lg-rounded overflow-hidden bg-blueish-gray/15 border border-blueish-gray/25  "
        style={{ boxShadow: "inset 0 0 10px white" }}
      >
        {/* text */}
        <div className="lg:p-6 p-4 relative lg:space-y-3 space-y-1.5 sm:w-1/2">
          <p className="text-28 ">Who are you really talking to?</p>
          <p className="text-18 opacity-70 leading-[1.2]! w-9/10">
            Learn everything about anyone before every call — where they work,
            what they do, and more.
          </p>
        </div>

        {/* img */}
        <div className="flex justify-end relative lg:py-6 sm:py-24 max-sm:p-4 sm:w-1/2">
          <img
            className="object-contain lg:scale-200 lg:translate-x-1/2 sm:scale-200 sm:translate-x-1/2  "
            src="/assets/demos/horion-for-sales/who.png"
          />
        </div>
      </div>

      {/* card 4 */}
      <div
        className="relative flex max-w-[550px] w-full flex-col justify-between lg-rounded overflow-hidden bg-blueish-gray/15 border border-blueish-gray/25  "
        style={{ boxShadow: "inset 0 0 10px white" }}
      >
        {/* img */}
        <div className="flex justify-end lg:pr-12 pr-6 relative max-sm:pb-4 ">
          <img
            className="w-3/4"
            src="/assets/demos/horion-for-sales/meeting-notes.png"
          />
        </div>

        {/* text */}
        <div className="lg:p-6 p-4 absolute bottom-0 left-0 lg:space-y-3 space-y-1.5">
          <p className="text-28 ">Beautiful meeting notes</p>
          <p className="text-18 opacity-70 leading-[1.2]! w-9/10">
            Instant shareable meeting notes generated by AI.
          </p>
        </div>
      </div>
    </section>
  );
}
